######################################################################
# Automatically generated by qmake (3.0) Mon Jul 4 16:57:36 2016
######################################################################

TEMPLATE = app
TARGET = spineel
INCLUDEPATH += .

# Input
HEADERS += lexer.h token.h tokenlist.h
SOURCES += lexer.cpp main.cpp token.cpp
